// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type EventsDocumentDataSlicesSlice = NhmEventSlice;

/**
 * Content for Events documents
 */
interface EventsDocumentData {
  /**
   * Slice Zone field in *Events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: events.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EventsDocumentDataSlicesSlice> /**
   * Meta Title field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: events.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: events.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventsDocumentData>,
    "events",
    Lang
  >;

type NhmEventDocumentDataSlicesSlice = NhmEventSlice;

/**
 * Content for NHM Event documents
 */
interface NhmEventDocumentData {
  /**
   * Heading field in *NHM Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This is the heading
   * - **API ID Path**: nhm_event.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *NHM Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This is the description
   * - **API ID Path**: nhm_event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *NHM Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nhm_event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NhmEventDocumentDataSlicesSlice>;
}

/**
 * NHM Event document from Prismic
 *
 * - **API ID**: `nhm_event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NhmEventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NhmEventDocumentData>,
    "nhm_event",
    Lang
  >;

export type AllDocumentTypes = EventsDocument | NhmEventDocument;

/**
 * Primary content in *NhmEvent → Default → Primary*
 */
export interface NhmEventSliceDefaultPrimary {
  /**
   * Heading field in *NhmEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: this is a heading
   * - **API ID Path**: nhm_event.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * location field in *NhmEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: this is the location
   * - **API ID Path**: nhm_event.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * date field in *NhmEvent → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: nhm_event.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Description field in *NhmEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: this is the description
   * - **API ID Path**: nhm_event.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for NhmEvent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NhmEventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NhmEventSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NhmEvent*
 */
type NhmEventSliceVariation = NhmEventSliceDefault;

/**
 * NhmEvent Shared Slice
 *
 * - **API ID**: `nhm_event`
 * - **Description**: NhmEvent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NhmEventSlice = prismic.SharedSlice<
  "nhm_event",
  NhmEventSliceVariation
>;

/**
 * Primary content in *TestSlice → Default → Primary*
 */
export interface TestSliceSliceDefaultPrimary {
  /**
   * Title field in *TestSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Test title
   * - **API ID Path**: test_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TestSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description
   * - **API ID Path**: test_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for TestSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestSlice*
 */
type TestSliceSliceVariation = TestSliceSliceDefault;

/**
 * TestSlice Shared Slice
 *
 * - **API ID**: `test_slice`
 * - **Description**: Test slice for MCP verification.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestSliceSlice = prismic.SharedSlice<
  "test_slice",
  TestSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EventsDocument,
      EventsDocumentData,
      EventsDocumentDataSlicesSlice,
      NhmEventDocument,
      NhmEventDocumentData,
      NhmEventDocumentDataSlicesSlice,
      AllDocumentTypes,
      NhmEventSlice,
      NhmEventSliceDefaultPrimary,
      NhmEventSliceVariation,
      NhmEventSliceDefault,
      TestSliceSlice,
      TestSliceSliceDefaultPrimary,
      TestSliceSliceVariation,
      TestSliceSliceDefault,
    };
  }
}
