// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type NhmEventDocumentDataSlicesSlice = ChurchEventSlice;

/**
 * Content for NHM Event documents
 */
interface NhmEventDocumentData {
  /**
   * Slice Zone field in *NHM Event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nhm_event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NhmEventDocumentDataSlicesSlice>;
}

/**
 * NHM Event document from Prismic
 *
 * - **API ID**: `nhm_event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NhmEventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NhmEventDocumentData>,
    "nhm_event",
    Lang
  >;

export type AllDocumentTypes = NhmEventDocument;

/**
 * Primary content in *ChurchEvent → Default → Primary*
 */
export interface ChurchEventSliceDefaultPrimary {
  /**
   * Event Title field in *ChurchEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New Haven Ministries Event
   * - **API ID Path**: church_event.default.primary.event_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  event_title: prismic.KeyTextField;

  /**
   * Event Description field in *ChurchEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New Haven Ministries event description placeholder
   * - **API ID Path**: church_event.default.primary.event_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  event_description: prismic.KeyTextField;

  /**
   * Event Image field in *ChurchEvent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: church_event.default.primary.event_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  event_image: prismic.ImageField<never>;

  /**
   * Cost field in *ChurchEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Event Cost
   * - **API ID Path**: church_event.default.primary.cost
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cost: prismic.KeyTextField;

  /**
   * Location field in *ChurchEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Location
   * - **API ID Path**: church_event.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;
}

/**
 * Default variation for ChurchEvent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChurchEventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ChurchEventSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ChurchEvent*
 */
type ChurchEventSliceVariation = ChurchEventSliceDefault;

/**
 * ChurchEvent Shared Slice
 *
 * - **API ID**: `church_event`
 * - **Description**: ChurchEvent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ChurchEventSlice = prismic.SharedSlice<
  "church_event",
  ChurchEventSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NhmEventDocument,
      NhmEventDocumentData,
      NhmEventDocumentDataSlicesSlice,
      AllDocumentTypes,
      ChurchEventSlice,
      ChurchEventSliceDefaultPrimary,
      ChurchEventSliceVariation,
      ChurchEventSliceDefault,
    };
  }
}
